
/* Drop Tables */
DROP TABLE IF EXISTS TB_PREFERENCE_INFO;
DROP TABLE IF EXISTS TB_PREFERENCE_MASTER;

/* Create Tables */
CREATE TABLE TB_PREFERENCE_MASTER
(
	PRF_SEQ serial NOT NULL UNIQUE,
	PRF_NAME varchar(100) NOT NULL,
	PRF_IMG varchar(200) NOT NULL,
	PRF_ORDER int NOT NULL,
	REMARKS varchar(100),
	USE_YN char(1),
	MOD_USER_ID varchar,
	REG_USER_ID varchar,
	MOD_DT timestamp with time zone,
	REG_DT timestamp with time zone NOT NULL,
	PRIMARY KEY (PRF_SEQ)
) WITHOUT OIDS;
ALTER TABLE plany.TB_PREFERENCE_MASTER OWNER to plany; 
GRANT ALL ON TABLE plany.TB_PREFERENCE_MASTER TO plany_admin;
GRANT SELECT ON TABLE plany.TB_PREFERENCE_MASTER TO plany_select; 
GRANT SELECT ON TABLE plany.TB_PREFERENCE_MASTER TO plany_dml;
GRANT ALL ON TABLE plany.TB_PREFERENCE_MASTER TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_PREFERENCE_MASTER TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_PREFERENCE_MASTER TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_PREFERENCE_MASTER_IDX_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821";
GRANT plany_select TO "H91256030";
GRANT plany_select TO "A91232220";
GRANT plany_select TO "A82157566";
GRANT plany_select TO "A82034649";


CREATE TABLE TB_PREFERENCE_INFO
(
	PRI_SEQ serial NOT NULL UNIQUE,
	PRF_SEQ int NOT NULL,
	CNTR_NO varchar(20) NOT NULL,
	MOD_DT timestamp with time zone,
	REG_DT timestamp with time zone NOT NULL,
	PRIMARY KEY (PRI_SEQ)
) WITHOUT OIDS;
ALTER TABLE plany.TB_PREFERENCE_INFO OWNER to plany; 
GRANT ALL ON TABLE plany.TB_PREFERENCE_INFO TO plany_admin;
GRANT SELECT ON TABLE plany.TB_PREFERENCE_INFO TO plany_select; 
GRANT SELECT ON TABLE plany.TB_PREFERENCE_INFO TO plany_dml;
GRANT ALL ON TABLE plany.TB_PREFERENCE_INFO TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_PREFERENCE_INFO TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_PREFERENCE_INFO TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_PREFERENCE_INFO_IDX_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821";
GRANT plany_select TO "H91256030";
GRANT plany_select TO "A91232220";
GRANT plany_select TO "A82157566";
GRANT plany_select TO "A82034649";

/* Comments */
COMMENT ON COLUMN TB_PREFERENCE_MASTER.PRF_SEQ IS '선호도 순번';
COMMENT ON COLUMN TB_PREFERENCE_MASTER.PRF_NAME IS '선호도 명';
COMMENT ON COLUMN TB_PREFERENCE_MASTER.PRF_IMG IS '선호도 이미지';
COMMENT ON COLUMN TB_PREFERENCE_MASTER.PRF_ORDER IS '선호도 정렬 순번';
COMMENT ON COLUMN TB_PREFERENCE_MASTER.REMARKS IS '비고';
COMMENT ON COLUMN TB_PREFERENCE_MASTER.USE_YN IS '사용여부(Y:사용, N:미사용)';
COMMENT ON COLUMN TB_PREFERENCE_MASTER.MOD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN TB_PREFERENCE_MASTER.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN TB_PREFERENCE_MASTER.MOD_DT IS '수정일자';

COMMENT ON COLUMN TB_PREFERENCE_INFO.PRI_SEQ IS '선호도  정보 순번';
COMMENT ON COLUMN TB_PREFERENCE_INFO.PRF_SEQ IS '선호도 순번';
COMMENT ON COLUMN TB_PREFERENCE_INFO.CNTR_NO IS '계약번호';
COMMENT ON COLUMN TB_PREFERENCE_INFO.MOD_DT IS '수정일자';
COMMENT ON COLUMN TB_PREFERENCE_INFO.REG_DT IS '등록일자';

/*사용자 선호도 정보 컬럼 추가*/
alter table plany.TB_USER add column PRF_FLAG char(1);
COMMENT ON COLUMN TB_USER.PRF_FLAG IS '선호도 플래그 값(Y:선택하기, null:Default, Z:다음에 하기, X:다시 안보기)';

alter table plany.TB_USER add column PRF_DT timestamp with time zone;
COMMENT ON COLUMN TB_USER.PRF_DT IS '선호도 등록 일자';


