
/* Drop Tables */
/*
DROP TABLE IF EXISTS plany.TB_ATTEND_DAY_CHECK;
DROP TABLE IF EXISTS plany.TB_ATTEND_INFO;
DROP TABLE IF EXISTS plany.TB_ENTRY_INFO;
DROP TABLE IF EXISTS plany.TB_EVENT_CONTENT;
DROP TABLE IF EXISTS plany.TB_GIFT_ISSUE_INFO;
DROP TABLE IF EXISTS plany.TB_YFRIENDS_CALLPLAN;
DROP TABLE IF EXISTS plany.TB_YFRIENDS_MENU_INFO;
DROP TABLE IF EXISTS plany.TB_EVENT_MASTER;
DROP TABLE IF EXISTS plany.TB_EVENT_MASTER_APPL;
DROP TABLE IF EXISTS plany.TB_REWARD_INFO;
DROP TABLE IF EXISTS plany.TB_GIFT_MASTER;
DROP TABLE IF EXISTS plany.TB_RECENT_CONTACT;
DROP TABLE IF EXISTS plany.TB_YFRIENDS_ROOM;
DROP TABLE IF EXISTS plany.TB_YFRIENDS_ROOM_INVT;
DROP TABLE IF EXISTS plany.TB_YFRIENDS_ROOM_JOIN;
*/

select * from TB_ATTEND_DAY_CHECK;
commit;
/* Create Tables */

CREATE TABLE plany.TB_ATTEND_DAY_CHECK
(
	CHK_SEQ serial NOT NULL UNIQUE,
	EVT_SEQ int4 NOT NULL,
	ATT_SEQ int4 NOT NULL,
	CNTR_NO varchar,
	CHECK_DAY int4,
	MOD_DT timestamptz,
	REG_DT timestamptz,
	PRIMARY KEY (CHK_SEQ)
) 
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_ATTEND_DAY_CHECK_idx01 ON plany.TB_ATTEND_DAY_CHECK USING btree (CHK_SEQ) ;
COMMENT ON COLUMN plany.TB_ATTEND_DAY_CHECK.CHK_SEQ IS '체크순번';
COMMENT ON COLUMN plany.TB_ATTEND_DAY_CHECK.EVT_SEQ IS '이벤트 순번';
COMMENT ON COLUMN plany.TB_ATTEND_DAY_CHECK.ATT_SEQ IS '출석체크 순번';
COMMENT ON COLUMN plany.TB_ATTEND_DAY_CHECK.CNTR_NO IS '계약번호';
COMMENT ON COLUMN plany.TB_ATTEND_DAY_CHECK.CHECK_DAY IS '출석체크확인 일차';
COMMENT ON COLUMN plany.TB_ATTEND_DAY_CHECK.MOD_DT IS '수정일자';
COMMENT ON COLUMN plany.TB_ATTEND_DAY_CHECK.REG_DT IS '등록일자';

ALTER TABLE plany.TB_ATTEND_DAY_CHECK OWNER to plany; 
GRANT ALL ON TABLE plany.TB_ATTEND_DAY_CHECK TO plany_admin;
GRANT SELECT ON TABLE plany.TB_ATTEND_DAY_CHECK TO plany_select; 
GRANT SELECT ON TABLE plany.TB_ATTEND_DAY_CHECK TO plany_dml;
GRANT ALL ON TABLE plany.TB_ATTEND_DAY_CHECK TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_ATTEND_DAY_CHECK TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_ATTEND_DAY_CHECK TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_ATTEND_DAY_CHECK_CHK_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;


select * from TB_ATTEND_INFO;
commit;

CREATE TABLE plany.TB_ATTEND_INFO
(
	ATT_SEQ serial NOT NULL UNIQUE,
	EVT_SEQ int4 NOT NULL,
	ISSUE_SEQ int4 NOT NULL,
	GIFT_DAY int4 NOT NULL,
	MOD_DT timestamptz,
	REG_DT timestamptz,
	PRIMARY KEY (ATT_SEQ)
) 
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_ATTEND_INFO_idx01 ON plany.TB_ATTEND_INFO USING btree (ATT_SEQ) ;
COMMENT ON COLUMN plany.TB_ATTEND_INFO.ATT_SEQ IS '출석체크 순번';
COMMENT ON COLUMN plany.TB_ATTEND_INFO.EVT_SEQ IS '이벤트 순번';
COMMENT ON COLUMN plany.TB_ATTEND_INFO.ISSUE_SEQ IS '상품발행순번';
COMMENT ON COLUMN plany.TB_ATTEND_INFO.GIFT_DAY IS '상품발행설정일차';
COMMENT ON COLUMN plany.TB_ATTEND_INFO.MOD_DT IS '수정일자';
COMMENT ON COLUMN plany.TB_ATTEND_INFO.REG_DT IS '등록일자';

ALTER TABLE plany.TB_ATTEND_INFO OWNER to plany; 
GRANT ALL ON TABLE plany.TB_ATTEND_INFO TO plany_admin;
GRANT SELECT ON TABLE plany.TB_ATTEND_INFO TO plany_select; 
GRANT SELECT ON TABLE plany.TB_ATTEND_INFO TO plany_dml;
GRANT ALL ON TABLE plany.TB_ATTEND_INFO TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_ATTEND_INFO TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_ATTEND_INFO TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_ATTEND_INFO_ATT_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;


select * from TB_ENTRY_INFO;
commit;

CREATE TABLE plany.TB_ENTRY_INFO
(
	ETR_SEQ serial NOT NULL UNIQUE,
	EVT_SEQ int4,
	GIFT_SEQ int4,
	ISSUE_SEQ int4,
	JOIN_SEQ int4,
	RECV_CNTR_NO varchar(20),
	RECV_NAME varchar(20),
	RECV_MOBILE_NO varchar(12),
	POST varchar(8),
	ADDR varchar(100),
	ADDR_DTL varchar(100),
	WIN_YN char(1),
	MOD_DT timestamptz,
	REG_DT timestamptz,
	PRIMARY KEY (ETR_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_ENTRY_INFO_idx01 ON plany.TB_ENTRY_INFO USING btree (ETR_SEQ) ;
COMMENT ON COLUMN plany.TB_ENTRY_INFO.ETR_SEQ IS '엔트리순번';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.EVT_SEQ IS '이벤트순번';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.GIFT_SEQ IS '상품순번';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.ISSUE_SEQ IS '상품발행순번';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.JOIN_SEQ IS '와이프렌즈참여순번';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.RECV_CNTR_NO IS '수신자 계약번호';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.RECV_NAME IS '수신자 이름';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.RECV_MOBILE_NO IS '수신자 전화번호';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.POST IS '우편번호';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.ADDR IS '주소';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.ADDR_DTL IS '주소상세';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.WIN_YN IS '당첨여부';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.MOD_DT IS '수정일자';
COMMENT ON COLUMN plany.TB_ENTRY_INFO.REG_DT IS '등록일자';

ALTER TABLE plany.TB_ENTRY_INFO OWNER to plany; 
GRANT ALL ON TABLE plany.TB_ENTRY_INFO TO plany_admin;
GRANT SELECT ON TABLE plany.TB_ENTRY_INFO TO plany_select; 
GRANT SELECT ON TABLE plany.TB_ENTRY_INFO TO plany_dml;
GRANT ALL ON TABLE plany.TB_ENTRY_INFO TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_ENTRY_INFO TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_ENTRY_INFO TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_ENTRY_INFO_ETR_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;



select * from TB_EVENT_CONTENT;
commit;

CREATE TABLE plany.TB_EVENT_CONTENT
(
	CON_SEQ serial NOT NULL UNIQUE,
	EVT_SEQ int4 NOT NULL,
	CON_TYPE char(5),
	CON_DTL_TYPE char(5),
	CON_DTL text,
	COLOR_CODE char(10),
	CON_ORDER int4,
	MOD_DT timestamptz,
	REG_DT timestamptz,
	PRIMARY KEY (CON_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_EVENT_CONTENT_idx01 ON plany.TB_EVENT_CONTENT USING btree (CON_SEQ) ;
COMMENT ON COLUMN plany.TB_EVENT_CONTENT.CON_SEQ IS '이벤트 내용 순번';
COMMENT ON COLUMN plany.TB_EVENT_CONTENT.EVT_SEQ IS '이벤트 순번';
COMMENT ON COLUMN plany.TB_EVENT_CONTENT.CON_TYPE IS '이벤트 내용 타입(자체구성:C0001, 외부HTML:C0002)';
COMMENT ON COLUMN plany.TB_EVENT_CONTENT.CON_DTL_TYPE IS '내용 상세 타입(C0001:텍스트(대), C0002:텍스트(중), C0003(소), C0004:이미지, C0005:영상(URL), C0006:라인, C0007:외부html태그)';
COMMENT ON COLUMN plany.TB_EVENT_CONTENT.CON_DTL IS '이벤트 내용 상세';
COMMENT ON COLUMN plany.TB_EVENT_CONTENT.COLOR_CODE IS '텍스트 색상코드';
COMMENT ON COLUMN plany.TB_EVENT_CONTENT.CON_ORDER IS '이벤트 상세 내용 순서';
COMMENT ON COLUMN plany.TB_EVENT_CONTENT.MOD_DT IS '수정일자';
COMMENT ON COLUMN plany.TB_EVENT_CONTENT.REG_DT IS '등록일자';

ALTER TABLE plany.TB_EVENT_CONTENT OWNER to plany; 
GRANT ALL ON TABLE plany.TB_EVENT_CONTENT TO plany_admin;
GRANT SELECT ON TABLE plany.TB_EVENT_CONTENT TO plany_select; 
GRANT SELECT ON TABLE plany.TB_EVENT_CONTENT TO plany_dml;
GRANT ALL ON TABLE plany.TB_EVENT_CONTENT TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_EVENT_CONTENT TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_EVENT_CONTENT TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_EVENT_CONTENT_CON_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;


select * from TB_EVENT_MASTER;
commit;

CREATE TABLE plany.TB_EVENT_MASTER
(
	EVT_SEQ serial NOT NULL UNIQUE,
	EVT_TYPE char(5) NOT NULL,
	EVT_TITLE varchar(50) NOT NULL,
	EVT_OPTION_TITLE varchar(200) NOT NULL,
	BTITLE_COLOR_CODE char(10) NOT NULL,
	EVT_SMALL_TITLE varchar(50) NOT NULL,
	STITLE_COLOR_CODE char(10) NOT NULL,
	EVT_START_DT char(12) NOT NULL,
	EVT_END_DT char(12) NOT NULL,
	GIFT_OFFER_TYPE char(5),
	ETR_OPEN_DT char(12),
	EVT_NOTE_YN char(1),
	EVT_NOTE varchar(2000),
	GIFT_CHOICE_TYPE char(5),
	ORDER_PRIORITY int4 DEFAULT 0 NOT NULL,
	BOTTOM_BUTTON_NAME varchar(20),
	LINK_TYPE char(5),
	LINK_URL varchar(200),
	SUB_LINK_URL varchar(200),
	EVT_LOGO_IMG varchar(200),
	MAIN_IMG varchar(200),
	BOARD_IMG varchar(200),
	EVT_DTL_TOP_IMG varchar(200),
	LNB_BOTTOM_IMG varchar(200),
	LNB_BOTTOM_IMG_YN varchar(200),
	REG_USER_ID varchar,
	EVT_CNT int4 DEFAULT 0 NOT NULL, 
	USE_YN char(1) NOT NULL,
	MOD_DT timestamptz,
	REG_DT timestamptz,
	PRIMARY KEY (EVT_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_EVENT_MASTER_idx01 ON plany.TB_EVENT_MASTER USING btree (EVT_SEQ) ;
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_SEQ IS '이벤트 순번';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_TYPE IS '이벤트 타입(G0001:일반이벤트, G0002:경품이벤트, G0003:매거진, G0004:Y프렌즈, G0005:출석체크, G0006:Y소식, G0007:게임)';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_TITLE IS '제목';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_OPTION_TITLE IS '제목';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.BTITLE_COLOR_CODE IS '제목색상코드';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_SMALL_TITLE IS '소제목';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.STITLE_COLOR_CODE IS '소제목색상코드';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_START_DT IS '이벤트 시작일자';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_END_DT IS '이벤트 종료 일자';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.GIFT_OFFER_TYPE IS '상품제공방식(상품없음:O0001, 선착순:O0002, 추첨:O0003)';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.ETR_OPEN_DT IS '당첨 발표일';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_NOTE_YN IS '유의사항제공여부';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_NOTE IS '유의사항';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.GIFT_CHOICE_TYPE IS '상품선택 방식(본인선택:C0001, 랜덤제공:C0002)';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.ORDER_PRIORITY IS '노출순위(0:최하위~100:최상위)';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.BOTTOM_BUTTON_NAME IS '하단버튼명';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.LINK_TYPE IS '링크타입(앱내링크:L0001, 랭덤제공:L0002)';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.LINK_URL IS '이벤트 링크URL';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.SUB_LINK_URL IS '이벤트 링크URL(iOS)';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_LOGO_IMG IS '이벤트 로고 이미지';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.MAIN_IMG IS '메인이미지';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.BOARD_IMG IS '게시판용 이미지';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_DTL_TOP_IMG IS '이벤트 상세 상단(배너) 이미지';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.LNB_BOTTOM_IMG IS '좌측 메뉴 하단 이미지';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.LNB_BOTTOM_IMG_YN IS '좌측 메뉴 하단 이미지 노출 여부';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.REG_USER_ID IS '등록자ID';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.EVT_CNT IS '이벤트조회건수';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.USE_YN IS '이벤트 사용여부';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.MOD_DT IS '수정일자';
COMMENT ON COLUMN plany.TB_EVENT_MASTER.REG_DT IS '등록일자';

ALTER TABLE plany.TB_EVENT_MASTER OWNER to plany; 
GRANT ALL ON TABLE plany.TB_EVENT_MASTER TO plany_admin;
GRANT SELECT ON TABLE plany.TB_EVENT_MASTER TO plany_select; 
GRANT SELECT ON TABLE plany.TB_EVENT_MASTER TO plany_dml;
GRANT ALL ON TABLE plany.TB_EVENT_MASTER TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_EVENT_MASTER TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_EVENT_MASTER TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_EVENT_MASTER_EVT_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;


select * from TB_EVENT_MASTER_APPL;
commit;

CREATE TABLE plany.TB_EVENT_MASTER_APPL
(
	APPL_SEQ serial NOT NULL UNIQUE,
	EVT_SEQ int NOT NULL,
	CNTR_NO varchar(20) NOT NULL,
	WIN_YN char(1) DEFAULT '''N''',
	NAME varchar(20),
	MOBILE_NO varchar(12),
	POST varchar(8),
	ADDR varchar(100),
	ADDR_DTL varchar(100),
	ADDR_CLEAR_YN char(1),
	JIBUN_ADDR varchar(100),
	JIBUN_ADDR_DTL varchar(100),
	ATTEND_DAY int,
	REG_DT timestamp with time zone,
	MOD_DT timestamp with time zone,
	PRIMARY KEY (APPL_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_EVENT_MASTER_APPL_idx01 ON plany.TB_EVENT_MASTER_APPL USING btree (APPL_SEQ) ;
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.APPL_SEQ IS '응모 SEQ';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.EVT_SEQ IS '이벤트SEQ';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.CNTR_NO IS '계약번호';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.WIN_YN IS '당첨여부';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.NAME IS '이름';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.MOBILE_NO IS '전화번호';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.POST IS '우편번호';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.ADDR IS '주소';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.ADDR_DTL IS '상세주소';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.ADDR_CLEAR_YN IS '주소 명확 구분: Y:명확, N: 불명확';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.ATTEND_DAY IS '출석일차';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.REG_DT IS '등록일시';
COMMENT ON COLUMN plany.TB_EVENT_MASTER_APPL.MOD_DT IS '수정일시';

ALTER TABLE plany.TB_EVENT_MASTER_APPL OWNER to plany; 
GRANT ALL ON TABLE plany.TB_EVENT_MASTER_APPL TO plany_admin;
GRANT SELECT ON TABLE plany.TB_EVENT_MASTER_APPL TO plany_select; 
GRANT SELECT ON TABLE plany.TB_EVENT_MASTER_APPL TO plany_dml;
GRANT ALL ON TABLE plany.TB_EVENT_MASTER_APPL TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_EVENT_MASTER_APPL TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_EVENT_MASTER_APPL TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_EVENT_MASTER_APPL_APPL_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;


select * from TB_GIFT_ISSUE_INFO;
commit;

CREATE TABLE plany.TB_GIFT_ISSUE_INFO
(
	ISSUE_SEQ serial NOT NULL UNIQUE,
	GIFT_SEQ int4 NOT NULL,
	EVT_SEQ int4 NOT NULL,
	GIFT_TYPE char(5) NOT NULL,
	GIFT_CNT int4 DEFAULT 0 NOT NULL,
	ISSUE_CNT int4 DEFAULT 0 NOT NULL,
	MOD_DT timestamptz,
	REG_DT timestamptz NOT NULL,
	PRIMARY KEY (ISSUE_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_GIFT_ISSUE_INFO_idx01 ON plany.TB_GIFT_ISSUE_INFO USING btree (ISSUE_SEQ) ;
COMMENT ON COLUMN plany.TB_GIFT_ISSUE_INFO.ISSUE_SEQ IS '상품발행순번';
COMMENT ON COLUMN plany.TB_GIFT_ISSUE_INFO.GIFT_SEQ IS '상품순번';
COMMENT ON COLUMN plany.TB_GIFT_ISSUE_INFO.EVT_SEQ IS '이벤트 순번';
COMMENT ON COLUMN plany.TB_GIFT_ISSUE_INFO.GIFT_TYPE IS '상품타입(오프라인:G0001, 온라인:G0002)';
COMMENT ON COLUMN plany.TB_GIFT_ISSUE_INFO.GIFT_CNT IS '이벤트 상품수량';
COMMENT ON COLUMN plany.TB_GIFT_ISSUE_INFO.ISSUE_CNT IS '상품발급수량';
COMMENT ON COLUMN plany.TB_GIFT_ISSUE_INFO.MOD_DT IS '수정일자';
COMMENT ON COLUMN plany.TB_GIFT_ISSUE_INFO.REG_DT IS '등록일자';

ALTER TABLE plany.TB_GIFT_ISSUE_INFO OWNER to plany; 
GRANT ALL ON TABLE plany.TB_GIFT_ISSUE_INFO TO plany_admin;
GRANT SELECT ON TABLE plany.TB_GIFT_ISSUE_INFO TO plany_select; 
GRANT SELECT ON TABLE plany.TB_GIFT_ISSUE_INFO TO plany_dml;
GRANT ALL ON TABLE plany.TB_GIFT_ISSUE_INFO TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_GIFT_ISSUE_INFO TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_GIFT_ISSUE_INFO TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_GIFT_ISSUE_INFO_ISSUE_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;



select * from TB_GIFT_MASTER;
commit;

CREATE TABLE plany.TB_GIFT_MASTER
(
	GIFT_SEQ serial NOT NULL UNIQUE,
	GIFT_TYPE char(5) NOT NULL,
	IMG_URL varchar(200) NOT NULL,
	GIFT_NAME varchar(100) NOT NULL,
	GIFT_INTRO varchar(1000),
	TOTAL_CNT int DEFAULT 0 NOT NULL,
	ISSUE_START_DT char(12),
	ISSUE_END_DT char(12),
	VALID_START_DT char(12) NOT NULL,
	VALID_END_DT char(12) NOT NULL,
	CUPN_USE_INFO_YN char(1),
	CUPN_USE_INFO varchar(2000),
	CUPN_ETC_YN char(1),
	CUPN_ETC varchar(2000),
	LAND_URL_TYPE char(5),
	LAND_URL varchar(200),
	USE_YN char(1) NOT NULL,
	MOD_DT timestamp with time zone,
	REG_DT timestamp with time zone,
	PRIMARY KEY (GIFT_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_GIFT_MASTER_idx01 ON plany.TB_GIFT_MASTER USING btree (GIFT_SEQ) ;
COMMENT ON COLUMN TB_GIFT_MASTER.GIFT_SEQ IS '상품순번';
COMMENT ON COLUMN TB_GIFT_MASTER.GIFT_TYPE IS '상품타입(배송용상품:G0001, 온라인상품:G0002)';
COMMENT ON COLUMN TB_GIFT_MASTER.IMG_URL IS '상품이미지 경로';
COMMENT ON COLUMN TB_GIFT_MASTER.GIFT_NAME IS '상품명';
COMMENT ON COLUMN TB_GIFT_MASTER.GIFT_INTRO IS '상품소개';
COMMENT ON COLUMN TB_GIFT_MASTER.TOTAL_CNT IS '총상품수량';
COMMENT ON COLUMN TB_GIFT_MASTER.ISSUE_START_DT IS '쿠폰발급시작일자';
COMMENT ON COLUMN TB_GIFT_MASTER.ISSUE_END_DT IS '쿠폰발급종료일자';
COMMENT ON COLUMN TB_GIFT_MASTER.VALID_START_DT IS '유효기간시작';
COMMENT ON COLUMN TB_GIFT_MASTER.VALID_END_DT IS '유효기간종료';
COMMENT ON COLUMN TB_GIFT_MASTER.CUPN_USE_INFO_YN IS '쿠폰 사용안내 여부';
COMMENT ON COLUMN TB_GIFT_MASTER.CUPN_USE_INFO IS '쿠폰사용안내';
COMMENT ON COLUMN TB_GIFT_MASTER.CUPN_ETC_YN IS '쿠폰유의사항사용여부';
COMMENT ON COLUMN TB_GIFT_MASTER.CUPN_ETC IS '쿠폰유의사항';
COMMENT ON COLUMN TB_GIFT_MASTER.LAND_URL_TYPE IS '랜딩타입(L0001:URL, L0002:APP)';
COMMENT ON COLUMN TB_GIFT_MASTER.LAND_URL IS '앱이동URL';
COMMENT ON COLUMN TB_GIFT_MASTER.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_GIFT_MASTER.MOD_DT IS '수정일자';
COMMENT ON COLUMN TB_GIFT_MASTER.REG_DT IS '등록일자';

ALTER TABLE plany.TB_GIFT_MASTER OWNER to plany; 
GRANT ALL ON TABLE plany.TB_GIFT_MASTER TO plany_admin;
GRANT SELECT ON TABLE plany.TB_GIFT_MASTER TO plany_select; 
GRANT SELECT ON TABLE plany.TB_GIFT_MASTER TO plany_dml;
GRANT ALL ON TABLE plany.TB_GIFT_MASTER TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_GIFT_MASTER TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_GIFT_MASTER TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_GIFT_MASTER_GIFT_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;


select * from TB_RECENT_CONTACT;
commit;

CREATE TABLE plany.TB_RECENT_CONTACT
(
	RCT_SEQ serial NOT NULL UNIQUE,
	CNTR_NO varchar(20),
	RECV_CNTR_NO varchar(20),
	RECV_MOBILE_NO varchar(20),
	RECV_NAME varchar(20),
	DATA_GIFT_TYPE char(5),
	REG_DT timestamptz,
	MOD_DT timestamptz,
	PRIMARY KEY (RCT_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_RECENT_CONTACT_idx01 ON plany.TB_RECENT_CONTACT USING btree (RCT_SEQ) ;
COMMENT ON COLUMN plany.TB_RECENT_CONTACT.RCT_SEQ IS '최근연락순번';
COMMENT ON COLUMN plany.TB_RECENT_CONTACT.CNTR_NO IS '계약번호';
COMMENT ON COLUMN plany.TB_RECENT_CONTACT.RECV_CNTR_NO IS '수신자 계약번호';
COMMENT ON COLUMN plany.TB_RECENT_CONTACT.RECV_MOBILE_NO IS '수신자 핸드폰번호';
COMMENT ON COLUMN plany.TB_RECENT_CONTACT.RECV_NAME IS '수신자 이름';
COMMENT ON COLUMN plany.TB_RECENT_CONTACT.DATA_GIFT_TYPE IS '보내기조르기구분(G0001:보내기,G0002:조르기)';
COMMENT ON COLUMN plany.TB_RECENT_CONTACT.REG_DT IS '등록일자';
COMMENT ON COLUMN plany.TB_RECENT_CONTACT.MOD_DT IS '수정일자';

ALTER TABLE plany.TB_RECENT_CONTACT OWNER to plany; 
GRANT ALL ON TABLE plany.TB_RECENT_CONTACT TO plany_admin;
GRANT SELECT ON TABLE plany.TB_RECENT_CONTACT TO plany_select; 
GRANT SELECT ON TABLE plany.TB_RECENT_CONTACT TO plany_dml;
GRANT ALL ON TABLE plany.TB_RECENT_CONTACT TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_RECENT_CONTACT TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_RECENT_CONTACT TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_RECENT_CONTACT_RCT_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;


select * from TB_REWARD_INFO;
commit;

CREATE TABLE plany.TB_REWARD_INFO
(
	REW_SEQ serial NOT NULL UNIQUE,
	GIFT_SEQ int4,	
	ISSUE_SEQ int4,
	CNTR_NO varchar,
	REW_ID varchar(500),
	ISSUE_YN char(1),
	ISSUE_DT timestamptz,
	MOD_DT timestamptz,
	REG_DT timestamptz,
	PRIMARY KEY (REW_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_REWARD_INFO_idx01 ON plany.TB_REWARD_INFO USING btree (REW_SEQ) ;
COMMENT ON COLUMN plany.TB_REWARD_INFO.REW_SEQ IS '리워드 순번';
COMMENT ON COLUMN plany.TB_REWARD_INFO.ISSUE_SEQ IS '발행순번';
COMMENT ON COLUMN plany.TB_REWARD_INFO.CNTR_NO IS '계약번호';
COMMENT ON COLUMN plany.TB_REWARD_INFO.REW_ID IS '리워드 고유번호';
COMMENT ON COLUMN plany.TB_REWARD_INFO.ISSUE_YN IS '발행여부';
COMMENT ON COLUMN plany.TB_REWARD_INFO.ISSUE_DT IS '발행일자';
COMMENT ON COLUMN plany.TB_REWARD_INFO.MOD_DT IS '수정일자';
COMMENT ON COLUMN plany.TB_REWARD_INFO.REG_DT IS '등록일자';

ALTER TABLE plany.TB_REWARD_INFO OWNER to plany; 
GRANT ALL ON TABLE plany.TB_REWARD_INFO TO plany_admin;
GRANT SELECT ON TABLE plany.TB_REWARD_INFO TO plany_select; 
GRANT SELECT ON TABLE plany.TB_REWARD_INFO TO plany_dml;
GRANT ALL ON TABLE plany.TB_REWARD_INFO TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_REWARD_INFO TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_REWARD_INFO TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_REWARD_INFO_REW_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;



select * from TB_YFRIENDS_CALLPLAN;
commit;


CREATE TABLE plany.TB_YFRIENDS_CALLPLAN
(
	CALL_SEQ serial NOT NULL UNIQUE,
	EM_SEQ int4 NOT NULL,
	PP_CD varchar(20),
	REG_DT timestamptz,
	PRIMARY KEY (CALL_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_YFRIENDS_CALLPLAN_idx01 ON plany.TB_YFRIENDS_CALLPLAN USING btree (CALL_SEQ) ;
COMMENT ON COLUMN plany.TB_YFRIENDS_CALLPLAN.CALL_SEQ IS '이벤트 메뉴 순번';
COMMENT ON COLUMN plany.TB_YFRIENDS_CALLPLAN.EM_SEQ IS '메뉴순번';
COMMENT ON COLUMN plany.TB_YFRIENDS_CALLPLAN.PP_CD IS '요금제코드';
COMMENT ON COLUMN plany.TB_YFRIENDS_CALLPLAN.REG_DT IS '등록일자';

ALTER TABLE plany.TB_YFRIENDS_CALLPLAN OWNER to plany; 
GRANT ALL ON TABLE plany.TB_YFRIENDS_CALLPLAN TO plany_admin;
GRANT SELECT ON TABLE plany.TB_YFRIENDS_CALLPLAN TO plany_select; 
GRANT SELECT ON TABLE plany.TB_YFRIENDS_CALLPLAN TO plany_dml;
GRANT ALL ON TABLE plany.TB_YFRIENDS_CALLPLAN TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_CALLPLAN TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_CALLPLAN TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_YFRIENDS_CALLPLAN_CALL_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;



select * from TB_YFRIENDS_MENU_INFO;
commit;


CREATE TABLE plany.TB_YFRIENDS_MENU_INFO
(
	EM_SEQ serial NOT NULL UNIQUE,
	EVT_SEQ int4 NOT NULL UNIQUE,
	MENU_NAME varchar(100) NOT NULL,
	MENU_URL varchar(500),
	MENU_START_DT char(12) NOT NULL,
	MENU_END_DT char(12) NOT NULL,
	DTL_TITLE varchar(100),
	DTL_ROOM_TITLE varchar(100),
	EVENT_DETAIL varchar(1000),
	AGE_START int4,
	AGE_END int4,
	MAX_ROOM_CNT int4,
	ANDRD_USE_YN char(1),
	IOS_USE_YN char(1),
	CALLPLAN_YN char(1) NOT NULL,
	USE_YN char(1) NOT NULL,
	MOD_DT timestamptz,
	REG_DT timestamptz,
	PRIMARY KEY (EM_SEQ)
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_YFRIENDS_MENU_INFO_idx01 ON plany.plany.TB_YFRIENDS_MENU_INFO USING btree (EM_SEQ) ;
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.EM_SEQ IS '메뉴순번';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.EVT_SEQ IS '이벤트 순번';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.MENU_NAME IS '메뉴명';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.MENU_URL IS '메뉴URL';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.MENU_START_DT IS '메뉴표시 시작 일자';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.MENU_END_DT IS '메뉴 표시 종료 일자';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.DTL_TITLE IS '와이프렌즈 메뉴 상세 제목';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.DTL_ROOM_TITLE IS '와이프렌즈 메뉴 상세 방 제목';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.EVENT_DETAIL IS '이벤트 설명';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.AGE_START IS '시작연령';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.AGE_END IS '종료연령';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.MAX_ROOM_CNT IS '와이틴프렌즈 룸카운트';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.ANDRD_USE_YN IS '안드로이드 사용여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.IOS_USE_YN IS 'IOS 사용여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.CALLPLAN_YN IS '요금제 적용 여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.USE_YN IS '메뉴 사용여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.MOD_DT IS '수정일자';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.REG_DT IS '등록일자';

ALTER TABLE plany.TB_YFRIENDS_MENU_INFO OWNER to plany; 
GRANT ALL ON TABLE plany.TB_YFRIENDS_MENU_INFO TO plany_admin;
GRANT SELECT ON TABLE plany.TB_YFRIENDS_MENU_INFO TO plany_select; 
GRANT SELECT ON TABLE plany.TB_YFRIENDS_MENU_INFO TO plany_dml;
GRANT ALL ON TABLE plany.TB_YFRIENDS_MENU_INFO TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_MENU_INFO TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_MENU_INFO TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_YFRIENDS_MENU_INFO_EM_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;




select * from TB_YFRIENDS_ROOM
commit;
/* Create Tables */

CREATE TABLE plany.TB_YFRIENDS_ROOM
(
	RM_SEQ serial NOT NULL UNIQUE,
	EM_SEQ int NOT NULL,
	MAX_JOIN_CNT int NOT NULL,
	REMARKS varchar(1000),
	DEL_YN char DEFAULT '''N''' NOT NULL,
	INVITED_FNSH_YN char DEFAULT '''N''' NOT NULL,
	JOIN_FNSH_YN char DEFAULT '''N''' NOT NULL,
	MOD_DT timestamp with time zone,
	REG_DT timestamp with time zone NOT NULL,
	GIFT_RCV_YN char DEFAULT '''N''' NOT NULL,
	FIRST_FNSH_DT timestamp with time zone,
	PRIMARY KEY (RM_SEQ)
) 
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_YFRIENDS_ROOM_idx01 ON plany.TB_YFRIENDS_ROOM USING btree (RM_SEQ) ;
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.RM_SEQ IS '방번호';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.EM_SEQ IS '메뉴순번';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.MAX_JOIN_CNT IS '방최대참여인원';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.REMARKS IS '비고';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.INVITED_FNSH_YN IS '모집완료여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.JOIN_FNSH_YN IS '참여만료여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.MOD_DT IS '수정일자';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.REG_DT IS '등록일자';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.GIFT_RCV_YN IS '경품신청여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM.FIRST_FNSH_DT IS '최초모집완료일';

ALTER TABLE plany.TB_YFRIENDS_ROOM OWNER to plany; 
GRANT ALL ON TABLE plany.TB_YFRIENDS_ROOM TO plany_admin;
GRANT SELECT ON TABLE plany.TB_YFRIENDS_ROOM TO plany_select; 
GRANT SELECT ON TABLE plany.TB_YFRIENDS_ROOM TO plany_dml;
GRANT ALL ON TABLE plany.TB_YFRIENDS_ROOM TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_ROOM TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_ROOM TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_YFRIENDS_ROOM_RM_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;



select * from TB_YFRIENDS_ROOM_INVT
commit;
/* Create Tables */

CREATE TABLE plany.TB_YFRIENDS_ROOM_INVT
(
	INVT_SEQ serial NOT NULL UNIQUE,
	RM_SEQ int NOT NULL,
	ASK_CNTR_NO varchar(20) NOT NULL,
	ASK_NAME varchar(20) NOT NULL,
	ASK_MOBILE_NO varchar(20),
	RCV_CNTR_NO varchar(20) NOT NULL,
	RCV_NAME varchar(20) NOT NULL,
	RCV_MOBILE_NO varchar(20),
	AGE_CHK_YN char DEFAULT '''N''' NOT NULL,
	CALLING_CHK_YN char DEFAULT '''N''' NOT NULL,
	DEVICE_CHK_YN char DEFAULT '''N''' NOT NULL,
	REG_DT timestamp with time zone,
	PRIMARY KEY (INVT_SEQ)
) 
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_YFRIENDS_ROOM_INVT_idx01 ON plany.TB_YFRIENDS_ROOM_INVT USING btree (INVT_SEQ) ;
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.INVT_SEQ IS '초대번호';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.RM_SEQ IS '방번호';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.ASK_CNTR_NO IS '초대요청자 계약번호';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.ASK_NAME IS '초대요청자명';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.ASK_MOBILE_NO IS '초대요청자 핸드폰번호';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.RCV_CNTR_NO IS '초대대상자 계약번호';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.RCV_NAME IS '초대대상자명';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.RCV_MOBILE_NO IS '초대대상자 핸드폰번호';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.AGE_CHK_YN IS '나이체크여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.CALLING_CHK_YN IS '요금제체크여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.DEVICE_CHK_YN IS '단말기 체크 여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_INVT.REG_DT IS '등록일자';

ALTER TABLE plany.TB_YFRIENDS_ROOM_INVT OWNER to plany; 
GRANT ALL ON TABLE plany.TB_YFRIENDS_ROOM_INVT TO plany_admin;
GRANT SELECT ON TABLE plany.TB_YFRIENDS_ROOM_INVT TO plany_select; 
GRANT SELECT ON TABLE plany.TB_YFRIENDS_ROOM_INVT TO plany_dml;
GRANT ALL ON TABLE plany.TB_YFRIENDS_ROOM_INVT TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_ROOM_INVT TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_ROOM_INVT TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_YFRIENDS_ROOM_INVT_INVT_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;



select * from TB_YFRIENDS_ROOM_JOIN
commit;
/* Create Tables */

CREATE TABLE plany.TB_YFRIENDS_ROOM_JOIN
(
	JOIN_SEQ serial NOT NULL UNIQUE,
	RM_SEQ int NOT NULL,
	JOIN_TYPE char(5),
	JOIN_CNTR_NO varchar(20),
	JOIN_NAME varchar(20),
	PP_CD varchar(20),
	DEL_YN char DEFAULT '''N''' NOT NULL,
	REG_DT timestamp with time zone DEFAULT now() NOT NULL,
	MOD_DT timestamp with time zone DEFAULT now()
) 
WITH (
	OIDS=FALSE
) ;
CREATE INDEX TB_YFRIENDS_ROOM_JOIN_idx01 ON plany.TB_YFRIENDS_ROOM_JOIN USING btree (JOIN_SEQ) ;
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_JOIN.JOIN_SEQ IS '방참여순번';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_JOIN.RM_SEQ IS '방번호';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_JOIN.JOIN_TYPE IS '참여구분(JN001 :방장, JN002:팀원)';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_JOIN.JOIN_CNTR_NO IS '참여자 계약번호';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_JOIN.JOIN_NAME IS '참여자명';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_JOIN.PP_CD IS '요금제코드';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_JOIN.DEL_YN IS '삭제여부';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_JOIN.REG_DT IS '등록일자';
COMMENT ON COLUMN plany.TB_YFRIENDS_ROOM_JOIN.MOD_DT IS '등록일자';

ALTER TABLE plany.TB_YFRIENDS_ROOM_JOIN OWNER to plany; 
GRANT ALL ON TABLE plany.TB_YFRIENDS_ROOM_JOIN TO plany_admin;
GRANT SELECT ON TABLE plany.TB_YFRIENDS_ROOM_JOIN TO plany_select; 
GRANT SELECT ON TABLE plany.TB_YFRIENDS_ROOM_JOIN TO plany_dml;
GRANT ALL ON TABLE plany.TB_YFRIENDS_ROOM_JOIN TO plany;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_ROOM_JOIN TO plany_dml; 
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE plany.TB_YFRIENDS_ROOM_JOIN TO "BOSDBI"; 
GRANT ALL ON SEQUENCE TB_YFRIENDS_ROOM_JOIN_JOIN_SEQ_SEQ TO "BOSDBI";
GRANT plany_select TO "H91246821" ;
GRANT plany_select TO "H91256030" ;
GRANT plany_select TO "A91232220" ;
GRANT plany_select TO "A82157566" ;
GRANT plany_select TO "A82034649" ;



/* Alter table TB_TERMS_AGREE */
alter table plany.TB_TERMS_AGREE add column opt2_terms_agree_yn char(1);
alter table plany.TB_TERMS_AGREE add column opt2_terms_chg_dt timestamptz;

COMMENT ON COLUMN plany.TB_TERMS_AGREE.opt2_terms_agree_yn IS '선택약관2 동의여부';
COMMENT ON COLUMN plany.TB_TERMS_AGREE.opt2_terms_chg_dt IS '선택약관2 수정일시';

/* Alter table TB_USER */
alter table plany.TB_USER add column birth_day char(8);

COMMENT ON COLUMN plany.TB_USER.birth_day IS '생년월일';


/* Alter table TB_YFRIENDS_MENU_INFO 생성 스크립트에 추가 완료
alter table plany.TB_YFRIENDS_MENU_INFO add column dtl_title varchar(100);
alter table plany.TB_YFRIENDS_MENU_INFO add column dtl_room_title varchar(100);

COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.dtl_title IS '와이프렌즈 메뉴 상세 제목';
COMMENT ON COLUMN plany.TB_YFRIENDS_MENU_INFO.dtl_room_title IS '와이프렌즈 메뉴 상세 방 제목';
*/